name: bloc_annotation
description: Annotations for bloc_annotation code generation package
version: 1.0.0
homepage: https://github.com/Myrkheimr/bloc_annotation/tree/main/bloc_annotation
repository: https://github.com/Myrkheimr/bloc_annotation
issue_tracker: https://github.com/Myrkheimr/bloc_annotation/issues
publish_to: none

topics:
  - annotation
  - bloc
  - cubit
  - flutter
  - dart

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
