name: bloc_meta_workspace

description: >-
  Monorepo for bloc_meta and bloc_meta_generator packages with examples.

environment:
    sdk: ^3.9.2

publish_to: none

workspace:
  - packages/bloc_meta
  - packages/bloc_meta_generator
  - examples/counter_cubit
  - examples/random_facts
  - examples/dog
