name: random_facts
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

resolution: workspace

# Add regular dependencies here.
dependencies:
  bloc_meta: any
  http: ^1.5.0
  bloc: ^9.1.0

dev_dependencies:
  build_runner: ^2.10.1
  lints: ^6.0.0
  test: ^1.25.6
  bloc_meta_generator: any