name: bloc_annotation_generator
description: >-
  Code generator for Flutter BLoC pattern components including Cubit, BLoC, Event, 
  and State classes. Automatically generates type-safe boilerplate code.
version: 1.0.0
homepage: https://github.com/Myrkheimr/bloc_annotation/tree/main/bloc_annotation_generator
repository: https://github.com/Myrkheimr/bloc_annotation
issue_tracker: https://github.com/Myrkheimr/bloc_annotation/issues
publish_to: none

topics:
  - builder
  - build-runner
  - bloc
  - cubit
  - code-generation
  - codegen
  - flutter
  - dart

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  analyzer: ^8.2.0
  build: ^4.0.1
  build_config: ^1.2.0
  code_builder: ^4.11.0
  dart_style: ^3.1.2
  source_gen: ^4.0.1
  bloc_annotation: any
  build_verify: ^3.1.1
  source_gen_test: ^1.3.2

dev_dependencies:
  build_runner: ^2.9.0
  lints: ^6.0.0
  test: ^1.25.6
